### 텐서 만들기

In [1]:
def describe(x):
    print('타입: {}'.format(x.type()))
    print('크기: {}'.format(x.shape))
    print('값: {}'.format(x))
    print()


In [2]:
import torch
describe(torch.Tensor(2, 3))

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: tensor([[0., 0., 0.],
        [0., 0., 0.]])



In [3]:
# 랜덤 초기화
describe(torch.rand(2, 3)) # 균등 분포
describe(torch.randn(2, 3)) # 표준 정규 분포

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: tensor([[0.9074, 0.1237, 0.8801],
        [0.6428, 0.5944, 0.0136]])

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: tensor([[ 1.1355, -0.7674,  1.2075],
        [ 0.8909,  0.5733, -0.3632]])



In [4]:
# filled() 메서드 사용
describe(torch.zeros(2, 3))
x = torch.ones(2, 3)
describe(x)
x.fill_(5)
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: tensor([[0., 0., 0.],
        [0., 0., 0.]])

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: tensor([[1., 1., 1.],
        [1., 1., 1.]])

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: tensor([[5., 5., 5.],
        [5., 5., 5.]])



In [5]:
# 파이썬 리스트로 텐서를 만들고 초기화 하기
x = torch.Tensor([[1,2,3],
                  [4,5,6]])
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: tensor([[1., 2., 3.],
        [4., 5., 6.]])



In [6]:
# 넘파이로 텐서를 만들고 초기화
import numpy as np
npy = np.random.rand(2, 3)
describe(torch.from_numpy(npy))
# 넘파이 기본 데이터 타입이 float64여서 동일하게 float64로 타입이 결정

타입: torch.DoubleTensor
크기: torch.Size([2, 3])
값: tensor([[0.8382, 0.8633, 0.6915],
        [0.9372, 0.4633, 0.1528]], dtype=torch.float64)



### 텐서 타입과 크기

In [7]:
x = torch.FloatTensor([[1, 2, 3],
                      [4, 5, 6]])
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: tensor([[1., 2., 3.],
        [4., 5., 6.]])



In [8]:
x = x.long()
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: tensor([[1, 2, 3],
        [4, 5, 6]])



In [9]:
# torch.Tensor -> 기본 torch.FloatTensor, 타입을 캐스팅해서 다른 타입 사용
# torch.tensor -> dtype을 지정해서 사용
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]], dtype=torch.int64)
describe(x)

x = x.float()
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: tensor([[1, 2, 3],
        [4, 5, 6]])

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: tensor([[1., 2., 3.],
        [4., 5., 6.]])



### 텐서 연산

In [10]:
x = torch.randn(2, 3)
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: tensor([[ 1.3445, -0.0735, -0.5299],
        [ 1.0780, -0.8770,  1.0029]])



In [11]:
describe(torch.add(x, x))

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: tensor([[ 2.6890, -0.1471, -1.0598],
        [ 2.1561, -1.7541,  2.0059]])



In [12]:
describe(x + x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: tensor([[ 2.6890, -0.1471, -1.0598],
        [ 2.1561, -1.7541,  2.0059]])



In [13]:
'''
텐서의 특정 차원에 적용할 수 있는 연산도 있음
2D 텐서는 행을 0, 열을 1로 표현
'''
# 차원별 텐서 연산
x = torch.arange(6)
describe(x)

x = x.view(2, 3)
describe(x)

타입: torch.LongTensor
크기: torch.Size([6])
값: tensor([0, 1, 2, 3, 4, 5])

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: tensor([[0, 1, 2],
        [3, 4, 5]])



In [14]:
describe(torch.sum(x, dim=0)) # 행 덧셈

타입: torch.LongTensor
크기: torch.Size([3])
값: tensor([3, 5, 7])



In [15]:
describe(torch.sum(x, dim=1)) # 열 덧셈

타입: torch.LongTensor
크기: torch.Size([2])
값: tensor([ 3, 12])



In [16]:
describe(torch.transpose(x, 0, 1))

타입: torch.LongTensor
크기: torch.Size([3, 2])
값: tensor([[0, 3],
        [1, 4],
        [2, 5]])



### 인덱싱, 슬라이싱, 연결

In [17]:
x = torch.arange(6).view(2, 3)
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: tensor([[0, 1, 2],
        [3, 4, 5]])



In [18]:
describe(x[:1, :2])

타입: torch.LongTensor
크기: torch.Size([1, 2])
값: tensor([[0, 1]])



In [19]:
describe(x[0, 1])

타입: torch.LongTensor
크기: torch.Size([])
값: 1



In [20]:
indicies = torch.LongTensor([0, 2])
describe(torch.index_select(x, dim=1, index=indicies)) # input: Tensor, dim=1 열 0과 2열을 선택

타입: torch.LongTensor
크기: torch.Size([2, 2])
값: tensor([[0, 2],
        [3, 5]])



In [21]:
indicies = torch.LongTensor([0, 0])
describe(torch.index_select(x, dim=0, index=indicies)) # 행에 대해서 0번째 행을 두 번 선택

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: tensor([[0, 1, 2],
        [0, 1, 2]])



In [22]:
row_indices = torch.arange(2).long()
col_indices = torch.LongTensor([0, 1])
describe(x[row_indices, col_indices]) # [0, 0], [1, 1] 선택
# 인덱스를 설정할 때 항상 long type

타입: torch.LongTensor
크기: torch.Size([2])
값: tensor([0, 4])



In [23]:
# 텐서 연결
x = torch.arange(6).view(2, 3)
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: tensor([[0, 1, 2],
        [3, 4, 5]])



In [24]:
describe(torch.cat([x, x], dim=0)) # 행을 기준으로 이어 붙힘

타입: torch.LongTensor
크기: torch.Size([4, 3])
값: tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])



In [25]:
describe(torch.cat([x, x], dim=1))

타입: torch.LongTensor
크기: torch.Size([2, 6])
값: tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])



In [26]:
describe(torch.stack([x, x])) # 차원 증가

타입: torch.LongTensor
크기: torch.Size([2, 2, 3])
값: tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])



In [27]:
# 텐서의 선형대수 계산: 행렬 곱셈
x1 = torch.arange(6).view(2, 3)
describe(x1)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: tensor([[0, 1, 2],
        [3, 4, 5]])



In [28]:
x2 = torch.ones(3, 2)
x2[:, 1] += 1 # 열 +1
describe(x2)

타입: torch.FloatTensor
크기: torch.Size([3, 2])
값: tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])



In [31]:
describe(torch.mm(x1.float(), x2)) # 형을 맞춰야 곱셈이 됨

타입: torch.FloatTensor
크기: torch.Size([2, 2])
값: tensor([[ 3.,  6.],
        [12., 24.]])



### 텐서와 계산 그래프

In [32]:
# 그래디언트 연산을 할 수 있는 텐서 만들기
x = torch.ones(2, 2, requires_grad=True)
# requires_grad 불리언 매개변수 True로 지정시 그레이디언트 기반 학습에 필요한 손실 함수와 텐서의 그레이디언트를 기로하는 부가 연산을 활성화
describe(x)
print(x.grad is None)


타입: torch.FloatTensor
크기: torch.Size([2, 2])
값: tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

True


In [34]:
y = (x + 2) * (x + 5) + 3
describe(y)
print(x.grad is None)

타입: torch.FloatTensor
크기: torch.Size([2, 2])
값: tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)

True


In [35]:
z = y.mean()
describe(z)
z.backward()
print(x.grad is None)

타입: torch.FloatTensor
크기: torch.Size([])
값: 21.0

False


### CUDA 텐서

In [38]:
# device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device = torch.device('mps' if torch.backends.mps.is_available() else 'cpu')

print(device)

mps


In [39]:
x = torch.rand(3, 3).to(device)
describe(x)

타입: torch.mps.FloatTensor
크기: torch.Size([3, 3])
값: tensor([[0.0943, 0.5747, 0.2655],
        [0.4133, 0.2030, 0.4168],
        [0.1339, 0.9065, 0.9217]], device='mps:0')



In [40]:
y = torch.rand(3, 3)
x + y
# cpu 와 gpu는 같이 연산 불가
'''
gpu로 데이터를 넣고 꺼내는 작업은 비용이 많이 들어감
따라서 병렬 계산은 gpu에서 수행하고 최종 결과만 cpu로 전송
cuda 장치가 여러개 있다면 CUDA_VISIBLE_DEVICES 환경 변수를 사용
'''

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, mps:0 and cpu!

### 연습 문제

In [51]:
# 1. 2D텐서를 만들고 차원 0 위치에 크기가 1인 차원을 추가
x = torch.rand(3, 3)
describe(x)
x = x.unsqueeze(0)
describe(x)


타입: torch.FloatTensor
크기: torch.Size([3, 3])
값: tensor([[0.2928, 0.3426, 0.4808],
        [0.4396, 0.1621, 0.6670],
        [0.6630, 0.3587, 0.1301]])

타입: torch.FloatTensor
크기: torch.Size([1, 3, 3])
값: tensor([[[0.2928, 0.3426, 0.4808],
         [0.4396, 0.1621, 0.6670],
         [0.6630, 0.3587, 0.1301]]])



In [52]:
# 2. 이전 텐서에 추가한 차원 삭제
x = x.squeeze(0)
describe(x)

타입: torch.FloatTensor
크기: torch.Size([3, 3])
값: tensor([[0.2928, 0.3426, 0.4808],
        [0.4396, 0.1621, 0.6670],
        [0.6630, 0.3587, 0.1301]])



In [53]:
# 3. 범위가 (3, 7)이고 크기가 5,3인 랜덤한 텐서를 만드세요
x = 3 + torch.rand(5, 3) * (7 - 3)
describe(x)
'''
rand -> 0~1범위 0~4범위로 스케일링 해주고 +3
'''

타입: torch.FloatTensor
크기: torch.Size([5, 3])
값: tensor([[5.3970, 6.9761, 4.3541],
        [4.6541, 4.3547, 4.9806],
        [3.2724, 3.0962, 6.1753],
        [4.5844, 5.5909, 6.1795],
        [3.9437, 6.7806, 3.1690]])



In [55]:
# 4. 정규 분포(평균=0, 표준편차=1)를 사용해 텐서를 만드세요
x = torch.randn(3, 3)
describe(x)

타입: torch.FloatTensor
크기: torch.Size([3, 3])
값: tensor([[ 0.7076,  0.7281,  0.0329],
        [-0.7973, -1.2629,  0.6950],
        [-0.4922, -0.1316,  0.5548]])



In [61]:
# 5. 텐서 torch.Tensor([1, 1, 1, 0, 1])에서 0이 아닌 원소의 인덱스를 추출
x = torch.Tensor([1, 1, 1, 0, 1])
print(x.count_nonzero())
torch.nonzero(x)

tensor(4)


tensor([[0],
        [1],
        [2],
        [4]])

In [67]:
# 6. 크기가 (3, 1)인 랜덤한 텐서를 만들고 네 벌을 복사해 쌓으세요
x = torch.rand(3, 1)
describe(torch.hstack([x]*4))

x.expand(3, 4)

타입: torch.FloatTensor
크기: torch.Size([3, 4])
값: tensor([[0.1438, 0.1438, 0.1438, 0.1438],
        [0.9092, 0.9092, 0.9092, 0.9092],
        [0.4344, 0.4344, 0.4344, 0.4344]])



tensor([[0.1438, 0.1438, 0.1438, 0.1438],
        [0.9092, 0.9092, 0.9092, 0.9092],
        [0.4344, 0.4344, 0.4344, 0.4344]])

In [69]:
# 7. 2차원 행렬 두 개(a=torch.rand(3, 4, 5), b=torch.rand(3, 5, 4))의 배치 행렬 곱셈을 계산
a=torch.rand(3, 4, 5)
b=torch.rand(3, 5, 4)
torch.bmm(a, b)

tensor([[[1.0108, 0.9477, 0.8401, 1.3131],
         [2.1093, 1.5091, 1.9701, 2.2013],
         [0.9323, 0.5244, 0.7375, 0.5675],
         [1.8795, 1.3459, 1.7055, 2.0167]],

        [[1.3568, 0.4564, 0.8571, 1.3340],
         [1.6210, 0.3888, 0.8786, 1.0893],
         [0.4218, 0.1995, 0.5243, 0.3414],
         [1.3709, 0.3879, 1.1309, 1.0373]],

        [[1.5920, 1.5553, 1.6033, 1.0661],
         [1.4483, 1.7265, 1.8073, 1.1049],
         [1.6601, 1.4358, 1.3991, 1.1090],
         [1.1321, 1.0752, 1.1583, 0.7712]]])

In [70]:
# 8. 3차원 행렬 a=torch.rand(3, 4, 5), 2차원 행렬 b=torch.rand(5, 4)의 배치 행렬 곱셈
a=torch.rand(3, 4, 5)
b=torch.rand(5, 4)
torch.matmul(a, b)

# torch.bmm(a, b.unsqueeze(0).expand(a.size(0), *b.size())

tensor([[[1.0869, 1.2099, 1.4758, 0.8696],
         [0.4130, 0.8840, 0.7591, 0.3228],
         [1.5958, 1.4865, 1.4685, 1.0337],
         [1.1135, 1.3028, 1.6322, 0.9489]],

        [[1.6340, 1.7159, 1.7992, 1.1331],
         [0.9275, 1.3561, 1.0644, 0.6378],
         [1.8795, 2.1915, 1.7894, 1.1804],
         [0.6121, 0.6970, 0.7649, 0.4963]],

        [[1.4164, 1.7680, 1.6943, 1.0346],
         [1.1411, 1.4394, 1.4034, 0.7877],
         [1.6216, 1.6968, 1.1517, 0.8894],
         [0.7630, 1.0037, 1.1948, 0.5716]]])